-- MySQL Script generated by MySQL Workbench
-- Fri Apr 17 23:48:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hospital` ;

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `hospital`.`pacientes` (
  `idpacientes` INT NOT NULL ,
  `imagen` VARCHAR(60) NULL,
  `nombre` VARCHAR(60) NULL,
  `tipoid` CHAR(3) NULL,
  `cedula` VARCHAR(30) NULL,
  `sexo` CHAR(1) NULL,
  `telefono` VARCHAR(45) NULL,
  `tiposangre` INT NULL,
  `email` VARCHAR(45) NULL,
  `idpaisnac` INT NULL,
  `iddistrito` INT NULL,
  `idcorregimiento` INT NULL,
  `idtipovivienda` INT NULL,
  `residencia` VARCHAR(60) NULL,
  `idhogar` VARCHAR(5) NOT NULL,
  `sintomatico` CHAR(1) NULL,
  `viajepais` CHAR(1) NULL,
  `contactoriesgo` CHAR(1) NULL,
  `cantpersonas` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idpacientes`))
ENGINE = InnoDB;

CREATE INDEX `identificador` ON `hospital`.`pacientes` (`idpacientes` ASC, `idhogar` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `hospital`.`contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`contactos` ;

CREATE TABLE IF NOT EXISTS `hospital`.`contactos` (
  `idcontactos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `idpaisnac` INT NULL,
  `tiposangre` INT NULL,
  `sexo` CHAR(1) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contact_idhogar` VARCHAR(5) NULL,
  PRIMARY KEY (`idcontactos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`sintomas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`sintomas` ;

CREATE TABLE IF NOT EXISTS `hospital`.`sintomas` (
  `idsintomas` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NULL,
  `estado` CHAR(1) NULL DEFAULT 'A',
  PRIMARY KEY (`idsintomas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`tiposangre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tiposangre` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tiposangre` (
  `idtiposangre` INT NOT NULL AUTO_INCREMENT,
  `sangre` VARCHAR(3) NULL,
  PRIMARY KEY (`idtiposangre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`sexo` ;

CREATE TABLE IF NOT EXISTS `hospital`.`sexo` (
  `idsexo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `valor` CHAR(1) NULL,
  PRIMARY KEY (`idsexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`paises` ;

CREATE TABLE IF NOT EXISTS `hospital`.`paises` (
  `idpaises` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(60) NULL,
  `riesgo` CHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`idpaises`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`distrito` ;

CREATE TABLE IF NOT EXISTS `hospital`.`distrito` (
  `iddistrito` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`iddistrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`corregimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`corregimiento` ;

CREATE TABLE IF NOT EXISTS `hospital`.`corregimiento` (
  `idcorregimiento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NULL,
  `iddistrito` INT NOT NULL,
  PRIMARY KEY (`idcorregimiento`, `iddistrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`tipovivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`tipovivienda` ;

CREATE TABLE IF NOT EXISTS `hospital`.`tipovivienda` (
  `idtipovivienda` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipovivienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`login` ;

CREATE TABLE IF NOT EXISTS `hospital`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`relacionpaciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`relacionpaciente` ;

CREATE TABLE IF NOT EXISTS `hospital`.`relacionpaciente` (
  `pacientes_idpacientes` INT NOT NULL,
  `sintomas_idsintomas` INT NULL,
  PRIMARY KEY (`pacientes_idpacientes`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hospital`.`viajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hospital`.`viajes` ;

CREATE TABLE IF NOT EXISTS `hospital`.`viajes` (
  `pacientes_idpacientes` INT NOT NULL,
  `paises_idpaises` INT NULL,
  PRIMARY KEY (`pacientes_idpacientes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Verificacion
-- -----------------------------------------------------

use hospital;
show tables;


